name: Deploy Static HTML to Azure Web App - TRG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D19FBAAF1C84053A0E7FD087901449E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F26DA579629E48AD8096578B93EB343C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74AA4F3ECCCC43E4B83AFF4AD5B5E7BC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TRG'
          slot-name: 'Production'
          package: .
